name: Deploy to EB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'


      - name: Install Dependency
        run: npm install


      - name: Generate Deployment Package
        run: zip -r deploy.zip *

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Seoul"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v14
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: qfeed-main-server
      #     environment_name: staging
      #     version_label: "qfeed-main-server${{ steps.format-time.outputs.replaced }}"
      #     region: ${{ secrets.REGION }}
      #     deployment_package: deploy.zip