name: Staging Deploy 

on:
  push:
    branches:
      - ci-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Seoul"

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_PR }}

      